{% set name = "xeger" %}
{% set version = "0.3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/xeger-{{ version }}.tar.gz
  sha256: 2a91341fc2c814b27917b8bd24e8d212c8a3b904d98e9a6703d27484c2cb0f82

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - xeger
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/crdoconnor/xeger
  summary: A library for generating random strings from a valid regular expression.
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - janjagusch
