schema_version: 1

context:
  name: xeger
  version: 0.3.5

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/xeger-${{ version }}.tar.gz
  sha256: 2a91341fc2c814b27917b8bd24e8d212c8a3b904d98e9a6703d27484c2cb0f82

build:
  number: 2
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - xeger
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  summary: A library for generating random strings from a valid regular expression.
  license: BSD-2-Clause
  license_file: LICENSE
  homepage: https://github.com/crdoconnor/xeger

extra:
  recipe-maintainers:
    - janjagusch
